# Generated by Django 5.0.1 on 2024-03-22 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='activity_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TravelPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('destination', models.CharField(max_length=20)),
                ('participants', models.PositiveIntegerField()),
                ('accommodation', models.CharField(max_length=20)),
                ('attractions', models.CharField(max_length=20)),
                ('restaurants', models.CharField(max_length=20)),
                ('experience', models.CharField(max_length=20)),
                ('exhibition', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('price', models.TextField()),
                ('photo', models.ImageField(upload_to='activity_photo/')),
                ('location', models.TextField()),
                ('telephone', models.TextField()),
                ('time', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.activity_category')),
            ],
        ),
    ]
