<<<<<<< HEAD
# Generated by Django 5.0.1 on 2024-04-19 06:41

import datetime
import django.db.models.deletion
=======
# Generated by Django 4.2.6 on 2024-04-17 05:03

>>>>>>> 118caa811f27f27ca0c66e2fd3edfc6ff0823cce
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('price', models.TextField()),
                ('photo', models.ImageField(upload_to='activity_photo/')),
                ('location', models.TextField()),
                ('telephone', models.TextField()),
                ('time', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('price', models.TextField()),
                ('photo', models.ImageField(upload_to='activity_photo/')),
                ('location', models.TextField()),
                ('telephone', models.TextField()),
                ('time', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.activitycategory')),
            ],
=======
            name='TripPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateField()),
                ('total_people', models.IntegerField()),
                ('departure_date', models.DateField(null=True)),
                ('destination', models.CharField(max_length=100)),
                ('transportation_method', models.CharField(max_length=100)),
                ('selected_accommodation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.accommodation')),
                ('selected_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planner.activity')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.activitycategory'),
>>>>>>> 118caa811f27f27ca0c66e2fd3edfc6ff0823cce
        ),
        migrations.CreateModel(
            name='TripPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateField()),
                ('total_people', models.IntegerField()),
                ('departure_date', models.DateField(default=datetime.date.today)),
                ('destination', models.CharField(max_length=100)),
                ('transportation_method', models.CharField(max_length=100)),
                ('selected_accommodation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.accommodation')),
                ('selected_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planner.activity')),
            ],
        ),
    ]
