# Generated by Django 5.0.1 on 2024-05-29 05:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tripplan',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friend_trip_plans', to=settings.AUTH_USER_MODEL),
        ),
    ]
