# Generated by Django 5.0.1 on 2024-03-19 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('price', models.TextField()),
                ('photo', models.ImageField(upload_to='activity_photo/')),
                ('location', models.TextField()),
                ('telephone', models.TextField()),
                ('time', models.TextField()),
            ],
        ),
    ]
