# Generated by Django 5.0.1 on 2024-06-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
