# Generated by Django 5.0.1 on 2024-06-25 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_chatroom_arrival_date_chatroom_departure_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='status',
            field=models.CharField(choices=[('recruiting', '모집 중'), ('completed', '모집 완료')], default='recruiting', max_length=20),
        ),
    ]
