# Generated by Django 5.0.1 on 2024-02-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tourist_spots/'),
        ),
        migrations.AlterField(
            model_name='touristspot',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='touristspot',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
