# Generated by Django 5.0.1 on 2024-03-05 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesights', '0002_touristspot_image_alter_touristspot_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regioncategory',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
