# Generated by Django 5.0.1 on 2024-04-12 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('thesights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='accommodations_photos/')),
                ('price', models.TextField()),
                ('details', models.TextField()),
                ('amenities', models.TextField()),
                ('quantity', models.IntegerField()),
                ('likes', models.PositiveIntegerField(default=0)),
                ('region_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thesights.regioncategory')),
            ],
        ),
    ]
