# Generated by Django 5.0.1 on 2024-04-26 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='trip_plans',
            field=models.ManyToManyField(related_name='users_trip_plans', to='planner.tripplan'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(related_name='customuser_user_permissions', to='auth.permission'),
        ),
    ]
