# Generated by Django 4.2.6 on 2024-05-28 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='trip_plans',
            field=models.ManyToManyField(related_name='users_trip_plans', to='planner.tripplan'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(related_name='customuser_user_permissions', to='auth.permission'),
        ),
        migrations.AddField(
            model_name='like',
            name='trip_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to='planner.tripplan'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'trip_plan')},
        ),
    ]
